

batch-size: 128
lr: 0.001

budget: 100000
ckpt-freq: 10000

project-name: "{dataset.name}-ec"

# model._type: classifier
# extractor:
#   _type: vit-raw
#   pretrained: yes
#   app:
#     image: input
#   name: vit_base_patch32_224
# head:
#   _type: linear


latent-dim: 128

enc-hidden: [512, 256]
cls-hidden: [256]
nonlin: mish

model:
  _type: classifier
  app:
    observation: embedding
    features: latent
    # prediction: prediction

head:
  _type: mlp
  hidden: <>cls-hidden

extractor:
  _type: mlp

  hidden: <>enc-hidden
  output-dim: <>latent-dim
  


env.task._type: multi-classification

log:
  macro: yes

# dataset:
#   _type: raw-coco
#   app:
#     class_presence: label
#   # split: val

dataset:
  _type: simple-coco
  

events.monitor:
  _type: wandb
  freqs:
    loss: 10
    macro: 10
    micro: 10
    roc_auc: 10


events.checkpointer:
  _type: checkpointer
  freq: <>ckpt-freq

optimizer._type: adam

trainer._type: trainer
planner._type: planner
reporter._type: reporter
unit: epochs


