# _meta.script_name: collect

path: "{dataset.dataroot}/embeddings/{dataset.name}-{model.name}.h5"

dataset._type: imagenet
# split: val

env.model._type: clip
env.model.gap.image_embedding: embedding
vit: ViT-B/32

products:
  - embedding
  - label
  - image_loc


