# _meta.script_name: collect

path: "/data/felix/coco/embeddings/{dataset.split}-{model.name}.h5"

# split: train
dataset:
  _type: raw-coco

env.model:
  _type: vit
  app:
    input: image
    features: embedding
name: vit_base_patch32_224

env.transform:
  _type: prep-rawimage

products:
  image_id: image_id
  pixels: image
  embedding: embedding
  class_presence: class_presence
  class_count: class_count
  # image ids
  