



_base: [m/optim/simple, uni]

project-name: "{dataset.name}-ced2"

model:
  _type: autoencoder
  _mod.supervised: yes
  app:
    loss: loss_rec
    features: latent


env.gt-intervention:
  _type: intervention/label

intervention.app.ambient: latent
# intervention.load: /data/felix/cache/checkpoints/vae128_coco_20250108_163649/ckpt_010000/interventions

env.intervention_module: <>intervention

env.semantic:
  _type: mechanism
  content: [<>env.task, <>model]
  external:
    loss_cls: loss_sem
    accuracy: accuracy_sem
    prediction: prediction_sem
  internal:
    label: intervention
    latent: probe

env.probe_response:
  _type: mechanism
  content: [<>model]
  external:
    latent: response
  internal:
    latent: probe
    observation: reconstruction


env.viz_latent_mag:
  _type: vecinfo
  app:
    vector: latent
    magnitude: latent_mag
    scale: latent_scale

env.viz_intv_mag:
  _type: vecinfo
  app:
    vector: probe
    magnitude: intv_mag
    scale: intv_scale

env.viz_support:
  _type: support
  app:
    src: latent
    tgt: probe

env.viz_pred_stats:
  _type: prediction-gap

  app:
    ambient: prediction
    intervened: prediction_sem

env.criterion:
  _type: multi-loss
  wts:
    rec: <>rec-wt
    # reg: <>reg-wt
    cls: <>cls-wt
    # con: <>con-wt
    # man: <>man-wt
    sem: <>sem-wt


rec-wt: 10
# reg-wt: 1
cls-wt: 1

sem-wt: 1

wandb:
  loss_rec: 10
  loss_cls: 10
  loss_sem: 10

  accuracy: 10
  accuracy_sem: 10

  rec_comparison: 1000
  intv_comparison: 1000

  latent_mag: 100
  latent_scale: 100
  intv_mag: 100
  intv_scale: 100
  amd: 100

  unchanged_f1: 500
  changed_f1: 500
  proximity_stats: 500

log:
  loss_rec: yes
  # loss_cls: yes
  loss_sem: yes
  
  accuracy: yes
  accuracy_sem: yes


