

_base: [a/mlp]

dataset:
  _type: coco-text

  app:
    embedding: observation

env.task:
  _type: multi-classification
  app:
    loss: loss_cls
    macro: accuracy

intervention.condition: <>interventions-text-path